const fs = require('fs');
const path = require('path');

// 1. Load the Skeleton Template
const templatePath = path.join(__dirname, '../src/app/master-skeleton.tsx');
if (!fs.existsSync(templatePath)) {
    console.error("master-skeleton.tsx not found. Run map-template.js first.");
    process.exit(1);
}
let html = fs.readFileSync(templatePath, 'utf8');

// 2. Load the Schema (for original bounds)
const schemaPath = path.join(__dirname, '../template-schema.json');
const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));

// 3. Load the Content (this would be generated by Gemini)
// For this test, we load content.json. If a field is missing, we fall back to the original text from the schema.
const contentPath = path.join(__dirname, '../content.json');
let content = {};
if (fs.existsSync(contentPath)) {
    content = JSON.parse(fs.readFileSync(contentPath, 'utf8'));
}

// 4. Inject Content & Apply Auto-Scaling
for (const [variableName, schemaData] of Object.entries(schema)) {
    if (variableName === 'SCROLL_TEXT') continue; // Handled separately by replace-scroll-text.js for now, or we can merge it later

    // Get the new text (from AI content, or fallback to original)
    const newText = content[variableName] || schemaData.originalText;
    
    // Auto-Scaling Logic (The Kastenprinzip)
    const originalLength = schemaData.originalCharCount;
    const newLength = newText.length;
    
    let injectedHTML = newText;
    
    // If the new text is significantly longer than original, shrink it so it fits the layout box
    const placeholder = `{{${variableName}}}`;
    
    if (newLength > originalLength && html.includes(placeholder)) {
        // Use square root for font-size scaling because font-size affects both width and height (area).
        const scaleFactor = Math.max(50, Math.floor(Math.sqrt(originalLength / newLength) * 100)); // Cap shrink at 50%
        
        // Find the opening tag right before the placeholder and inject the style directly into it.
        // This avoids creating <span> wrappers that break Webflow's GSAP SplitText animation.
        const regex = new RegExp(`<([^>]+)>(\\s*)${placeholder}`, 'g');
        
        // First try to inject the style into the parent tag
        html = html.replace(regex, (match, p1, p2) => {
            let newP1 = p1;
            const styleAttr = `font-size: ${scaleFactor}%;`;
            if (newP1.includes('style="')) {
                newP1 = newP1.replace('style="', `style="${styleAttr} `);
            } else {
                newP1 = `${newP1} style="${styleAttr}"`;
            }
            return `<${newP1}>${p2}${newText}`;
        });
        
        // Catch any remaining placeholders that weren't immediately preceded by a tag
        html = html.split(placeholder).join(newText);
    } else {
        // Normal replacement without scaling
        html = html.split(placeholder).join(newText);
    }
}

// 5. Save the final rendered page
const pagePath = path.join(__dirname, '../src/app/page.tsx');
fs.writeFileSync(pagePath, html);
console.log('Successfully injected content and applied auto-scaling! Generated page.tsx.');
